services:
  postgres:
    ports:
      - 5432:5432
    build: ./postgres
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 10s

    volumes:
      - pg_volume:/var/lib/postgresql

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://monitoring:01766@postgres:5432/vov_project?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

  redis:
    ports:
      - 6379:6379
    build: ./redis
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "admin_password", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - redis_data:/data

  redis-exporter:
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis://monitoring:01766@redis:6379
    depends_on:
      - redis
    networks:
      - app_network

  make_data:
    build: ./make_data
    networks:
      - app_network
    depends_on:
      backend:
        condition: service_healthy

  backend:
    ports:
      - 8000:8000
    build: ./backend
    networks:
      - app_network
    volumes:
      - backend_volume:/app/src/images

    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8000 || exit 0" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - 8080:80
    networks:
      - app_network
    depends_on:
      backend:
        condition: service_healthy

  prometheus:
    networks:
      - app_network
    build: ./prometheus
    depends_on:
      backend:
        condition: service_healthy

  grafana:
    networks:
      - app_network
    build: ./grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

networks:
  app_network:
    driver: bridge

volumes:
  pg_volume:
  backend_volume:
  redis_data:
