services:
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 10s

    volumes:
      - pg_volume:/var/lib/postgresql

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "admin_password", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - 8000:8000
    networks:
      - app_network
    volumes:
      - backend_volume:/app/src/images

    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8000 || exit 0" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - 80:80
    networks:
      - app_network
    depends_on:
      backend:
        condition: service_healthy

networks:
  app_network:
    driver: bridge

volumes:
  pg_volume:
  backend_volume:
  redis_data:
